#!/bin/bash
read -p "请输入远程主机的IP地址:" address
expect << eof
spawn ssh -o StrictHostKeyChecking=no $address
expect "password" {send "123456\n"}
expect "#" {send "rm -rf /etc/yum.repos.d/*\n"}
expect "#" {send "yum-config-manager --add ftp://192.168.4.254/rhel7\n"}
expect "#" {send "echo gpgcheck=0 >> /etc/yum.repos.d/*\n"}
expect "#" {send "yum repolist\n"}
expect "]#" {send "exit\n"}
eof
#expect "#" {send "yum -y install sssd\n"}
#expect "#" {send "systemctl restart httpd\n"}
#expect "#" {send "systemctl enable httpd\n"}
